import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// Generates the Kaam Khata self-declared income certificate.
///
/// Cross-platform:
/// ✅ Android
/// ✅ Web (Chrome)
/// ✅ Windows
class IncomeCertificatePdfGenerator {
  const IncomeCertificatePdfGenerator._();

  static Future<Uint8List> generate({
    required String certificateId,
    required String workerName,
    required String address,
    required double averageMonthlyIncome,
    required DateTime generatedOn,
    required int validForDays,
    required String disclaimer,
  }) async {
    final pdf = pw.Document();

    final validUntil = generatedOn.add(
      Duration(days: validForDays),
    );

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              /// Header
              pw.Row(
                mainAxisAlignment:
                    pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    "KAMAAI",
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColor.fromHex("#2E7D32"),
                    ),
                  ),
                  pw.Text(
                    "Certificate ID\n$certificateId",
                    textAlign: pw.TextAlign.right,
                    style: const pw.TextStyle(
                      fontSize: 10,
                    ),
                  ),
                ],
              ),

              pw.SizedBox(height: 10),

              pw.Divider(),

              pw.SizedBox(height: 24),

              pw.Center(
                child: pw.Text(
                  "SELF DECLARED\nINCOME CERTIFICATE",
                  textAlign: pw.TextAlign.center,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 30),

              _row(
                "Worker Name",
                workerName,
              ),

              _row(
                "Address",
                address,
              ),

              _row(
                "Average Monthly Income",
                "₹ ${averageMonthlyIncome.toStringAsFixed(0)}",
              ),

              _row(
                "Generated On",
                "${generatedOn.day}/${generatedOn.month}/${generatedOn.year}",
              ),

              _row(
                "Valid Until",
                "${validUntil.day}/${validUntil.month}/${validUntil.year}",
              ),

              pw.SizedBox(height: 28),

              pw.Text(
                "Declaration",
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 13,
                ),
              ),

              pw.SizedBox(height: 8),

              pw.Text(
                disclaimer,
                style: const pw.TextStyle(
                  fontSize: 11,
                  color: PdfColors.grey700,
                ),
              ),

              pw.Spacer(),

              pw.Row(
                mainAxisAlignment:
                    pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment:
                    pw.CrossAxisAlignment.end,
                children: [
                  pw.Column(
                    crossAxisAlignment:
                        pw.CrossAxisAlignment.start,
                    children: [
                      pw.Container(
                        width: 170,
                        height: 1,
                        color: PdfColors.grey600,
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        "Self Attested Signature",
                        style: const pw.TextStyle(
                          fontSize: 10,
                        ),
                      ),
                    ],
                  ),

                  pw.BarcodeWidget(
                    barcode: pw.Barcode.qrCode(),
                    data:
                        "KAMAAI-INCOME-$certificateId",
                    width: 80,
                    height: 80,
                  ),
                ],
              ),

              pw.SizedBox(height: 16),

              pw.Center(
                child: pw.Text(
                  "Generated by Kamaai",
                  style: const pw.TextStyle(
                    fontSize: 9,
                    color: PdfColors.grey600,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _row(
    String label,
    String value,
  ) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(
        vertical: 6,
      ),
      child: pw.Row(
        crossAxisAlignment:
            pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 170,
            child: pw.Text(
              label,
              style: const pw.TextStyle(
                fontSize: 11,
                color: PdfColors.grey700,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// Preview PDF
  static Future<void> preview(
    Uint8List pdfBytes,
  ) async {
    await Printing.layoutPdf(
      onLayout: (_) async => pdfBytes,
    );
  }

  /// Share / Download PDF
  static Future<void> share(
    Uint8List pdfBytes,
  ) async {
    await Printing.sharePdf(
      bytes: pdfBytes,
      filename: "kamaai_income_certificate.pdf",
    );
  }
}