// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: '1:720728932838:ios:dece03aa1dca34b4aad627',
    messagingSenderId: '720728932838',
    projectId: 'kamaai-2b7d9',
    storageBucket: 'kamaai-2b7d9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: '1:720728932838:ios:dece03aa1dca34b4aad627',
    messagingSenderId: '720728932838',
    projectId: 'kamaai-2b7d9',
    storageBucket: 'kamaai-2b7d9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: '1:720728932838:web:aa879704f3d4eed4aad627',
    messagingSenderId: '720728932838',
    projectId: 'kamaai-2b7d9',
    authDomain: 'kamaai-2b7d9.firebaseapp.com',
    storageBucket: 'kamaai-2b7d9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: '1:720728932838:web:aa879704f3d4eed4aad627',
    messagingSenderId: '720728932838',
    projectId: 'kamaai-2b7d9',
    authDomain: 'kamaai-2b7d9.firebaseapp.com',
    storageBucket: 'kamaai-2b7d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: '1:720728932838:android:956b702067e4bc8caad627',
    messagingSenderId: '720728932838',
    projectId: 'kamaai-2b7d9',
    storageBucket: 'kamaai-2b7d9.firebasestorage.app',
  );
}
